shortly_project/shortly_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.create_short_url, name='create_short_url'),
    path('<str:short_url>/', views.redirect_to_original_url, name='redirect_to_original_url'),
    path('get_list', views.get_shortened_urls_list, name='get_url_list')
]

shortly_project/shortly_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('shortly_app.urls'))
]

shortly_project/shortly_app/models.py
from django.db import models
import string
import random

def generate_random_short_url():
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(6))

class ShortURL(models.Model):
    original_url = models.URLField()
    short_url = models.CharField(max_length=6, unique=True, default=generate_random_short_url)

shortly_project/shortly_app/forms.py
from django import forms
from .models import ShortURL

class ShortURLForm(forms.ModelForm):
    class Meta:
        model = ShortURL
        fields = ['original_url']

shortly_project/shortly_app/views.py
from django.shortcuts import render, redirect
from .models import ShortURL
from .forms import ShortURLForm


def create_short_url(request):
    if request.method == 'POST':

        form = ShortURLForm(request.POST)
        urls_list = ShortURL.objects.all()

        if form.is_valid():
            short_url_obj = form.save()
            original_url = form.cleaned_data.get('original_url')
            # print(original_url)
            short_url = short_url_obj.short_url
            return render(request=request,template_name= 'shortend_url.html',context= {'urls_list':urls_list, 'short_url': short_url, "original_url":original_url})

    else:
        form = ShortURLForm()

    return render(request=request,template_name= 'create_short_url_form.html',context= {'form': form})

def redirect_to_original_url(request, short_url):
    short_url_obj = ShortURL.objects.get(short_url=short_url)

    return redirect(short_url_obj.original_url)

def get_shortened_urls_list(request):
    urls_list = ShortURL.objects.all()

    return render(request=request,template_name= 'shortend_url_list.html',context= {'urls_list':urls_list,})

shortly_project/shortly_app/templates/create_short_url_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Shortly - Create Short URL</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-top: 40px;
        }

        form {
            max-width: 800px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
        }

        form label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        form input[type="url"] {
            width: 100%;
            padding: 8px;
            font-size: 16px;
            border: 1px solid #ddd;
            border-radius: 5px;
        }

        form button {
            display: block;
            width: 100%;
            padding: 10px;
            margin-top: 20px;
            font-size: 16px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        form button:hover {
            background-color: #0056b3;
        }


    </style>
</head>
<body>
    <h1>Shortly - URL Shortener</h1>
        <div style="display: flex; flex-direction: column; justify-content: center; align-items: center; background-color: #A1CCD1; height: 700px;">
            <form method="post" style="width: 800px;">
                {% csrf_token %}
                <label for="id_original_url">Enter the Full URL:</label>
                {{ form.original_url }}
                <button type="submit">Shorten URL</button>
            </form>
        </div>
    </div>
</body>
</html>

shortly_project/shortly_app/templates/shortend_url.html
<!DOCTYPE html>
<html>
<head>
    <title>Shortly - Success</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-top: 40px;
        }

        p {
            text-align: center;
            margin-top: 20px;
            font-size: 18px;
            background-color: #fff;
            padding: 20px;
        }

        a {
            color: #007bff;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div>
        <div>
            <h1>URL Shortening Complete</h1>
            <p>Long URL: <a href="{{ original_url }}">{{ original_url }}</a></p>
            <p>Short URL: <a href="{{ short_url }}">{{ short_url }}</a></p>
        </div>
        <div>
            <h1 style="text-align: left;">Other shortened URLS</h1>
            <table>
                <tr>
                    <th>Original URL</th>
                    <th>Short URL</th>
                </tr>


                {% for url in urls_list %}
                <tr>
                    <td><a href="{{ original_url }}">{{ url.original_url }}</a></td>
                    <td><a href="{{ short_url }}">{{ url.short_url }}</a></td>
                </tr>
                {%endfor%}
            </table>
        </div>
    </div>
</body>
</html>

shortly_project/shortly_app/templates/shortened_url_list.html
<!DOCTYPE html>
<html>
    <body>
        <div>
            <h1 style="text-align: left;">Other shortened URLS</h1>
            <table>
                <tr>
                    <th>Original URL</th>
                    <th>Short URL</th>
                </tr>
        
        
                {% for url in urls_list %}
                <tr>
                    <td><a href="{{ original_url }}">{{ url.original_url }}</a></td>
                    <td><a href="{{ short_url }}">{{ url.short_url }}</a></td>
                </tr>
                {%endfor%}
            </table>
        </div>
    </body>
</html>